services:
  jacb:
    image: 192.168.4.9:5000/jacb:dev
    container_name: jacb
    restart: always
    ports:
      - "3500:3000"
    environment:
      NODE_OPTIONS: --dns-result-order=ipv4first
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

